stages:
  - build
  - deploy


build:
  stage: build
  script:
    - echo "我是 build"
  


pages: # job 的名称必须要是 pages
  stage: deploy
  retry:
    max: 2

  script: # 生成站点
    - mkdir public
    - cp index.html public/index.html
  artifacts: # 制品
    paths:
      - public