stages:
  - deploy
  


pages: # job 的名称必须要是 pages
  stage: deploy
  tags:
  - build
  retry:
    max: 2

  script: # 生成站点
    - mkdir public
    - cp -r src/* public/
  artifacts: # 制品
    paths:
      - public