stages:
  - deploy
  


pages: # job 的名称必须要是 pages
  stage: deploy
  tags:
  - build
  retry:
    max: 2
  hooks:
    pre_get_sources_script:
      - git config --global http.sslVerify false

  script: # 生成站点
    - mkdir public
    - cp src/* public/
  artifacts: # 制品
    paths:
      - public